### ISSUE TITLE
FBI uploads to DocCloud Failing

### ISSUE THREAD

**Issue by JPatBrown** [MuckRock/muckrock#991] opened 2016-06-16 20:00 UTC
Mike Best flagged [this request](https://www.muckrock.com/foi/united-states-of-america-10/myles-ambrose-25532/#files) - if you try to view the file on the page, this comes up:
![zero](https://cloud.githubusercontent.com/assets/9255253/16131135/9231f8e8-33da-11e6-9ba2-ee99255c50b6.jpg)
Though if you download the file, it comes up fine. 
I checked out a couple of older FBI requests and the [same problem came up](https://www.muckrock.com/foi/united-states-of-america-10/ms-magazine-24050/#file-88053). I took a look at DocCloud, and apparently it's a recurring problem with [FBI releases](https://www.documentcloud.org/search/Account:%20659-mitchell-kotler%20Source:%20%22Federal%20Bureau%20of%20Investigation%22).
![importfailed](https://cloud.githubusercontent.com/assets/9255253/16131208/12bfc13e-33db-11e6-9c4d-767d3bab7ca6.jpg)
 Though cover letters (and releases in the ~10 page range) are fine. Is this on our end or theirs? And can we force a reset?

**Comment by freddymartinez9** [comment] 2016-12-01 03:51
if someone has logs or a way to reproduce this, please send it to me. I can try to debug it

**Comment by mitchelljkotler** [comment] 2017-02-09 16:43
This problem is on document cloud's end.  Ted confirmed it for me - at this point their is no way to automate reprocessing the documents.  But there is now an open issue for it:
https://github.com/documentcloud/documentcloud/issues/443
Closing as the problem is not on our end.

**Closed by mitchelljkotler** 2017-02-09 16:43 UTC
Labels: bug, high, requests
