### ISSUE TITLE
Resolved New Agency Tasks should have more info.

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#1040] opened 2016-08-12 23:16 UTC
This task was resolved: https://www.muckrock.com/task/new-agency/90685/

The user flagged the request to say that the request was sent to the wrong place. It appears the task was treated as though it was rejected. However, the user had included the necessary information for the new agency and there's no good reason for way it should have been anything but approved. It's unclear whether this is a technical or a user/staff error. We should have a more clear way to tell how such a task was resolved.

**Comment by mitchelljkotler** [comment] 2017-12-14 18:36
This is basically a more specific dupe of #657

**Closed by mitchelljkotler** 2017-12-14 18:36 UTC
Labels: agencies, duplicate, low, tasks
