### ISSUE TITLE
Add "contact user" button to user profile

### ISSUE THREAD

**Issue by blipblitz** [MuckRock/muckrock#1676] opened 2019-06-20 15:32 UTC
Sometimes I just want to generally contact a user without going through the process of creating a Zoho ticket or associating the communication with a particular request

**Comment by blipblitz** [comment] 2019-07-31 14:54
Bump.

**Comment by morisy** [comment] 2019-08-09 19:55
Duplicate of #1676

**Closed by morisy** 2019-08-09 19:55 UTC
